### ISSUE TITLE
i3 extractor out of date with truth columns

### ISSUE THREAD

**Issue by BozianuLeon** [icecube/graphnet#169]
In i3ecxtractor.py the I3TruthExtractor does not take "interaction_time" out of i3 files. But then in train_model.py and others the SQLiteDataset attempts to extract this truth column, where it does not exist. I am not sure if this is a relic from a previous study into vertex reconstruction or if some pre-existing databases contain intereaction_time but these two should probably agree.

**Comment by briedel** [comment]
The code raises some questions for me.... It seems like all the input data needed is put into a SQLLite database or is in a table format, i.e. each entry is the same data types and lengths. Wouldnt it make more sense to dump the data into an HDF5 file or a pandas data frame and work with it like that rather than inside icetray? I would imagine this could speed up the training and execution significantly.

**Comment by RasmusOrsoe** [comment]
Hi @briedel!

I saw your comment just now. We convert i3 files to SQLite databases and from the SQLite databases we then do our development (Training, validation, plotting etc.). So IceTray is only involved in the sqlite database production, which is done once. It's a quite performant format with minimal memory overhead, and is quite a bit easier to introduce to students than i3-files and IceTray (in my experience). The setup as is quite capable of keeping gpu's fed so we don't suffer from GPU throttling!

Rasmus

**Comment by briedel** [comment]
Hi @RasmusOrsoe, 

One thing to note is that HDF5 (in my experience) is a little easier to work with than SQLLite. You can combine the files more easily (good when you are dumping more than one file in parallel) and the API doesn’t necessarily depend on SQL calls (little easier for students).  IceTray also has build in HDF5 support, so you can dump in python or C++.

Benedikt

**Comment by asogaard** [comment]
Hi @BozianuLeon,
As you are the author of this issue, I wanted to check back in whether this is still an active concern?

**Comment by BozianuLeon** [comment]
Thanks for bringing this up again @asogaard, the /data/constants.py file still contains interaction_time as a truth variable for IceCube86 and upgrade, which in the vast majority of plotting/analysis scripts has to be manually ignored/deleted. If this is something we wish to continue with it should be extracted (or at least given a padding value) from i3 files. If interaction_time is no longer used/deprecated then it should be removed from constants.py

**Comment by asogaard** [comment]
Thanks, @BozianuLeon! For truth variables I think it makes sense that the dataset/-loader should "fail gracefully", i.e. just produce a warning if a request variable is not present rather than failing outright, since we rarely use all of the available truth variables. I still think it makes sense to specify the _nominal_ set of truth variables that we expect to be present for each detector, and warn if the data being processed do not contain all of these. I will open an issue for this.
